.SH NAME
shellshocked \- a shockingly good shell

.SH SYNOPSIS
.B shellshocked
[\fIOPTION\fR]... [\fICOMMAND\fR [ARGUMENT]...]

.SH DESCRIPTION
Shellshocked is a super cool shell program that allows you to execute commands and navigate through your system using a command-line interface. It provides a stylish and interactive shell experience with additional cool features to make your terminal sessions awesome!

.SH OPTIONS
.TP
\fB\-h, \-\-help\fR
Display help message and exit.

.TP
\fB\-v, \-\-version\fR
Display version information and exit.

.SH COMMANDS
.TP
\fBexit\fR
Exit the shell.

.TP
\fBcd [DIRECTORY]\fR
Change the current directory to DIRECTORY. If no DIRECTORY is provided, change to the home directory.

.TP
\fBenv\fR
Print the current environment.

.SH USAGE
.PP
After installing Shellshocked, you can run it by typing:
.B hsh
at the command prompt. Once inside the shell, you can enter commands as you would in a regular shell.

.SH EXAMPLES
.PP
To list files in the current directory:
.B hsh
$ ls

.PP
To change directory to a specific location:
.B hsh
$ cd /path/to/directory

.PP
To print the current working directory:
.B hsh
$ pwd

.SH EXIT STATUS
Shellshocked returns a zero exit status if the command is successful, and a non-zero exit status otherwise.

.SH SEE ALSO
The README file included with the Shellshocked distribution.

.SH AUTHOR
Your Name <your.email@example.com>

.SH REPORTING BUGS
Please report bugs to <https://github.com/your-username/shellshocked/issues>.

.SH COPYRIGHT
Copyright © 2024 Your Name. This is free software: you are free to modify and redistribute it. There is NO WARRANTY, to the extent permitted by law.
